### ISSUE TITLE
Not showing dropdown suggestions for tags

### ISSUE THREAD

**Issue by chrissv** [dimtion/Shaarlier#33]
I upgraded phones and of course installed Shaarlier. It works fine, but one thing I see different. I have 3 tags which start with 2: 2save, 2look, 2buy.

On my old phone, when I would start typing "2" in the tags field, it would show me all 3 tags which start with 2 in a drop-down so I could choose which one I wanted.

On my new phone, it doesn't show me anything - it just makes me type in the tag completely. The link saves in my shaarli correctly with the tag, so everything seems to be working.

Old phone: LG G5, running Android 7.0
New phone: LG V30, running Android 7.1.2
Shaarlier version: 1.4.0-alpha

Any ideas why I should see different behavior? Let me know if I can provide any additional information.

**Comment by dimtion** [comment]
I assume this might be a duplicate of #29 ? The tags appears under the keyboard that hide them.

**Comment by chrissv** [comment]
Could be - I didn't see that. But I did notice that the next day, the dropdown suggestions *did* appear. Strange...

**Comment by dimtion** [comment]
Hello,
I have just pushed a set of patches that should fix this issue. If you would like to test the patch, please let me know, I'll build an alpha release for you.

**Comment by chrissv** [comment]
Hi, thank you. Yes, I would be happy to test it. I can side load *.apk files with no problems.
I still get intermittent tag suggestions with the production version.

**Comment by dimtion** [comment]
Hi,

I've published an alpha version of the next release: https://github.com/dimtion/Shaarlier/releases/tag/v1.5.0a1

Please let me know if you have any remark or if you encounter any bug.

**Comment by chrissv** [comment]
Thank you. Installed just fine, no problems so far. I will let you know.

**Comment by dimtion** [comment]
Thanks for your time, the release is now in production: https://github.com/dimtion/Shaarlier/releases/tag/v1.5.0

Please let me know if you have any issue.
